//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Percepciones.Libro
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class PercepcionesEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto PercepcionesEntities usando la cadena de conexión encontrada en la sección 'PercepcionesEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public PercepcionesEntities() : base("name=PercepcionesEntities", "PercepcionesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PercepcionesEntities.
        /// </summary>
        public PercepcionesEntities(string connectionString) : base(connectionString, "PercepcionesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto PercepcionesEntities.
        /// </summary>
        public PercepcionesEntities(EntityConnection connection) : base(connection, "PercepcionesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DOC_NC_AG> DOC_NC_AG
        {
            get
            {
                if ((_DOC_NC_AG == null))
                {
                    _DOC_NC_AG = base.CreateObjectSet<DOC_NC_AG>("DOC_NC_AG");
                }
                return _DOC_NC_AG;
            }
        }
        private ObjectSet<DOC_NC_AG> _DOC_NC_AG;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DOC_NC_AG. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDOC_NC_AG(DOC_NC_AG dOC_NC_AG)
        {
            base.AddObject("DOC_NC_AG", dOC_NC_AG);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PercepcionesModel", Name="DOC_NC_AG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DOC_NC_AG : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DOC_NC_AG.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static DOC_NC_AG CreateDOC_NC_AG(global::System.Int32 id)
        {
            DOC_NC_AG dOC_NC_AG = new DOC_NC_AG();
            dOC_NC_AG.ID = id;
            return dOC_NC_AG;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_CLIENTE
        {
            get
            {
                return _CODIGO_CLIENTE;
            }
            set
            {
                OnCODIGO_CLIENTEChanging(value);
                ReportPropertyChanging("CODIGO_CLIENTE");
                _CODIGO_CLIENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CODIGO_CLIENTE");
                OnCODIGO_CLIENTEChanged();
            }
        }
        private global::System.String _CODIGO_CLIENTE;
        partial void OnCODIGO_CLIENTEChanging(global::System.String value);
        partial void OnCODIGO_CLIENTEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_NC
        {
            get
            {
                return _CODIGO_NC;
            }
            set
            {
                OnCODIGO_NCChanging(value);
                ReportPropertyChanging("CODIGO_NC");
                _CODIGO_NC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CODIGO_NC");
                OnCODIGO_NCChanged();
            }
        }
        private global::System.String _CODIGO_NC;
        partial void OnCODIGO_NCChanging(global::System.String value);
        partial void OnCODIGO_NCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                OnFECHAChanging(value);
                ReportPropertyChanging("FECHA");
                _FECHA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FECHA");
                OnFECHAChanged();
            }
        }
        private global::System.String _FECHA;
        partial void OnFECHAChanging(global::System.String value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTO
        {
            get
            {
                return _MONTO;
            }
            set
            {
                OnMONTOChanging(value);
                ReportPropertyChanging("MONTO");
                _MONTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO");
                OnMONTOChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTO;
        partial void OnMONTOChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PERCEPCION
        {
            get
            {
                return _PERCEPCION;
            }
            set
            {
                OnPERCEPCIONChanging(value);
                ReportPropertyChanging("PERCEPCION");
                _PERCEPCION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PERCEPCION");
                OnPERCEPCIONChanged();
            }
        }
        private Nullable<global::System.Decimal> _PERCEPCION;
        partial void OnPERCEPCIONChanging(Nullable<global::System.Decimal> value);
        partial void OnPERCEPCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE_CLIENTE
        {
            get
            {
                return _NOMBRE_CLIENTE;
            }
            set
            {
                OnNOMBRE_CLIENTEChanging(value);
                ReportPropertyChanging("NOMBRE_CLIENTE");
                _NOMBRE_CLIENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBRE_CLIENTE");
                OnNOMBRE_CLIENTEChanged();
            }
        }
        private global::System.String _NOMBRE_CLIENTE;
        partial void OnNOMBRE_CLIENTEChanging(global::System.String value);
        partial void OnNOMBRE_CLIENTEChanged();

        #endregion
    
    }

    #endregion
    
}
